### ISSUE TITLE
Fees and authority keys modifications

### ISSUE THREAD

**Issue by iurage** [mithraiclabs/openbook-psy#2]
1. Currently, the `fee_sweeper` and `disable_authority` set in the deployed program is owned by the OpenBook DAO. We should change this to a PsyDAO owned address to have more flexibility and control over their usage.
2. `Base` fee tier is charged on OpenBook markets (see [discussion](https://github.com/openbook-dex/program/pull/5)) which includes:
- Maker Rebate: 2bps
- Referrer Rebate: 2bps
- Taker Fee: 4bps
In the context of PsyFi auctions, the vault is the "taker", which ends up paying 4bps to the option buyer and UI. My recommendation is to set `Base` fee to 0bps, so we have a cleaner & more transparent pricing structure entirely through vault fees.

**Comment by tomjohn1028** [comment]
Reference commits

Change fees: https://github.com/mithraiclabs/openbook-psy/commit/f2ffb5eee7cf2d9265c639b63d6e28962a791670
Change authorities: https://github.com/openbook-dex/program/commit/63ea6022f0ebab386373ad6f4d812425199791d6
